version: '3.8'

services:
  qr_code_app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      QR_CODE_DIR: /app/qr_codes
      FILL_COLOR: red
      BACK_COLOR: white
    volumes:
      - ./qr_codes:/app/qr_codes  # Maps the local 'qr_codes' directory to '/app/qr_codes' in the container
    command: ["python", "main.py", "--url", "https://github.com/Krishna-Sathvika-Ganni/IS601-HOMEWORK7.git"]  # Adjust if needed
